version: "3.9"

networks:
  hostname-net:

services:
  nginx-hostname:
    image: nginx:stable-alpine
    container_name: "${NGINX_CONTAINER_NAME}"
    ports:
        - "${NGINX_PORT_HTTP}:80"
        - "${NGINX_PORT_SSL}:443"
    volumes:
      - ../backend/:/var/www/project/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/ssl:/etc/nginx/ssl/
    extra_hosts:
      - "hostname.loc:127.0.0.1"
    depends_on:
      - php-hostname
      - db-hostname
    networks:
      - hostname-net

  php-hostname:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: "${PHP_CONTAINER_NAME}"
    ports:
      - "${PHP_PORT}:9000"
    volumes:
      - ../backend/:/var/www/project/
    networks:
      - hostname-net

  db-hostname:
    image: mariadb:10.5.10
    container_name: "${DB_CONTAINER_NAME}"
    ports:
      - ${MYSQL_PORT}:3306
    expose:
      - ${MYSQL_PORT}
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    #restart: always # always restart unless stopped manually
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - hostname-net
